apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-v1
  namespace: demo
  labels:
    app: whoami-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami-v1
  template:
    metadata:
      labels:
        app: whoami-v1
    spec:
      containers:
        - name: whoami
          image: traefik/whoami:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-v1
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: whoami-v1
  ports:
    - port: 80
      targetPort: 80
      name: http
